spring.application.name=subscriptions
spring.datasource.url=jdbc:postgresql://localhost:5432/subs_and_recs
spring.datasource.username=subscriber
spring.datasource.password=like
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml